INSERT INTO public.authors (id, name, initials, book_title, book_id, bio, back_cover, photo_url) VALUES
('miralpeix', 'Mercedes Miralpeix', 'MM', 'Posturas', 'posturas', 'Es Licenciada en Filosofía por la Universidad Nacional de Salta (UNSa). Docente en la Facultad de Humanidades de la UNSa e investigadora especializada en el pensamiento político y filosófico de Walter Benjamin y Hannah Arendt. Realizó sus estudios doctorales en Filosofía en la Universidad Nacional de La Plata (UNLP) con beca del CONICET. Es autora de numerosos artículos en revistas académicas y ha coordinado proyectos de filosofía con niños y jóvenes en la región.', 'Este libro es un encuentro entre dos formas de pensamiento: la escritura de Mercedes Miralpeix y la pintura de Virginia Montaldi. Ni una teoría que explica, ni una obra que ilustra: aquí lo que se abre es un diálogo crítico, feminista y situado. Las pinturas de Montaldi convocan una experiencia sensible del arte, y Miralpeix responde con una escritura que piensa desde el cuerpo y sus pliegues. Una invitación a mirar de otra manera.', NULL),
('pantaleon', 'Jorge F. Pantaleón', 'JP', 'Circulantes', 'circulantes', 'Es antropólogo, disciplina desde la cual comenzó a interrogar los vínculos entre técnica, política y vida cotidiana. Actualmente es profesor en el Departamento de Antropología de la Universidad de Montreal e investigador del Centre de Recherches Internationales de esa misma universidad. Ha codirigido la Cátedra de Estudios de las Américas y fue director de la Cátedra de Estudios del México Contemporáneo.', 'Este libro es, ante todo, un intercambio: entre disciplinas, entre territorios, entre imaginaciones, entre imágenes, entre reflexiones, entre personas. Jorge F. Pantaleón retoma su larga trayectoria investigando cómo nos relacionamos con el dinero —como valor, como creencia, como memoria y como vínculo— y la entrelaza con las provocadoras intervenciones artísticas de Sergio Díaz sobre los billetes. Así surge una conversación situada y desobediente.', NULL),
('ulm', 'Hernán Ulm', 'HU', 'Desbordes', 'desborde', 'Es filósofo. En sus trabajos ha indagado sobre el arte, la imagen, la política y la estética contemporánea. Ha desarrollado un pensamiento original sobre el modo en que el arte ha transformado nuestro modo de concebir, conocer e interpretar la realidad. Esta es su tercera publicación luego de Cuestión de imágenes y Rituales de la percepción: artes, técnicas, políticas.', 'En la época de la imagen digital y su hiper-visualización, este libro explora los dibujos de Roly Arias como un espacio donde los límites se transforman y contaminan. La escritura reflexiva de Hernán Ulm nos invita a sumergirnos en esta experiencia estética, política y colectiva del presente. Memoria viva de un ojo estallado en cruce con la historia, el amor y la discrepancia.', NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    initials = EXCLUDED.initials,
    book_title = EXCLUDED.book_title,
    book_id = EXCLUDED.book_id,
    bio = EXCLUDED.bio,
    back_cover = EXCLUDED.back_cover;
